language: generic
os: linux
dist: focal
services:
  - docker

before_install:
  - docker build -t saschawissel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true saschawissel/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-740670160476"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY